[project]
name = "nano281"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nbmake>=1.5.5",
    "pandas>=2.2.3",
    "pymatgen>=2025.3.10",
    "pytest>=8.3.5",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
]
